# Generated by Django 4.1.3 on 2023-06-10 06:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo_Postular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Crear_Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.FloatField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.crear_categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='El nombre solo debe contener letras', regex='^[a-zA-Z]*$')], verbose_name='Nombre')),
                ('ap_paterno', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='El apellido solo debe contener letras', regex='^[a-zA-Z]*$')], verbose_name='Apellido Paterno')),
                ('ap_materno', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='El apellido solo debe contener letras', regex='^[a-zA-Z]*$')], verbose_name='Apellido Materno')),
                ('comuna', models.IntegerField(choices=[[0, 'Santiago'], [1, 'Providencia'], [2, 'Las Condes'], [3, 'La Florida'], [4, 'Ñuñoa'], [5, 'Vitacura'], [6, 'Maipú'], [7, 'Puente Alto'], [8, 'La Reina'], [9, 'Peñalolén'], [10, 'Macul'], [11, 'San Joaquín'], [12, 'La Cisterna'], [13, 'Independencia'], [14, 'Cerrillos'], [15, 'Renca'], [16, 'Quinta Normal'], [17, 'Lo Prado'], [18, 'Pudahuel']], verbose_name='Comuna donde vives')),
                ('edad', models.IntegerField(validators=[django.core.validators.MinValueValidator(18, message='No puedes postular siendo menor de edad'), django.core.validators.MaxValueValidator(100, message='La edad no puede ser mayor a 100.')], verbose_name='Edad')),
                ('celular', phonenumber_field.modelfields.PhoneNumberField(help_text='Ejemplo: +56 9 12345678  o  9 45216387', max_length=128, region=None, unique=True, verbose_name='Celular')),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='Ingresa una dirección de correo electrónico válida.')], verbose_name='Correo Electrónico')),
                ('nivel_ed', models.IntegerField(choices=[[0, 'Basica Completa'], [1, 'Media Completa'], [2, 'Superior']], verbose_name='Nivel educacional')),
                ('nivel_excel', models.IntegerField(choices=[[0, 'Basico'], [1, 'Intermedio'], [2, 'Alto'], [3, 'Profesional']], verbose_name='Nivel de manejo en Excel')),
                ('experiencia', models.IntegerField(choices=[[0, 'De 0 a 2 años'], [1, 'De 3 a 5 años'], [2, 'De 6 a 8 años'], [3, 'Sobre 9 años']], verbose_name='Experiencia en el area')),
                ('describir_experiencia', models.TextField(help_text='Máximo 250 caracteres.', max_length=250, verbose_name='Describa su Experiencia')),
                ('cv', models.FileField(blank=True, null=True, upload_to='CVs', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])], verbose_name='Adjuntar Currículum Vitae')),
                ('disponibilidad', models.BooleanField(verbose_name='Disponiblidad inmediata')),
                ('fecha_postulacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Postulacion')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.cargo_postular', verbose_name='Cargo a postular')),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_orden', models.DateTimeField(auto_now_add=True)),
                ('completo', models.BooleanField(default=False)),
                ('transaccion_id', models.CharField(max_length=200, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='DireccionEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=200, null=True)),
                ('ciudad', models.CharField(max_length=200, null=True)),
                ('comuna', models.CharField(max_length=200, null=True)),
                ('codigo_postal', models.CharField(max_length=200, null=True)),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.cliente')),
                ('orden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.orden')),
            ],
        ),
        migrations.CreateModel(
            name='ArticuloOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(blank=True, default=0, null=True)),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('orden', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.orden')),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.producto')),
            ],
        ),
    ]
