# Generated by Django 4.1.3 on 2023-05-25 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo_Postular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('ap_paterno', models.CharField(max_length=15)),
                ('ap_materno', models.CharField(max_length=15)),
                ('comuna', models.IntegerField(choices=[[0, 'Santiago'], [1, 'Providencia'], [2, 'Las Condes'], [3, 'La Florida'], [4, 'Ñuñoa'], [5, 'Vitacura'], [6, 'Maipú'], [7, 'Puente Alto'], [8, 'La Reina'], [9, 'Peñalolén'], [10, 'Macul'], [11, 'San Joaquín'], [12, 'La Cisterna'], [13, 'Independencia'], [14, 'Cerrillos'], [15, 'Renca'], [16, 'Quinta Normal'], [17, 'Lo Prado'], [18, 'Pudahuel']])),
                ('edad', models.IntegerField()),
                ('celular', models.IntegerField()),
                ('email', models.EmailField(max_length=30)),
                ('nivel_ed', models.IntegerField(choices=[[0, 'Basica Completa'], [1, 'Media Completa'], [2, 'Superior']])),
                ('nivel_excel', models.IntegerField(choices=[[0, 'Basico'], [1, 'Intermedio'], [2, 'Alto'], [3, 'Profesional']])),
                ('experiencia', models.IntegerField(choices=[[0, 'De 0 a 2 años'], [1, 'De 3 a 5 años'], [2, 'De 6 a 8 años'], [3, 'Sobre 9 años']])),
                ('describir_experiencia', models.TextField()),
                ('disponibilidad', models.BooleanField()),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.cargo_postular')),
            ],
        ),
        migrations.DeleteModel(
            name='Nivel_Educacion',
        ),
    ]
