# Generated by Django 4.1.3 on 2023-05-26 20:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_cargo_postular_postulacion_delete_nivel_educacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulacion',
            name='fecha_postulacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de postulacion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postulacion',
            name='ap_materno',
            field=models.CharField(max_length=15, verbose_name='Apellido Materno'),
        ),
        migrations.AlterField(
            model_name='postulacion',
            name='ap_paterno',
            field=models.CharField(max_length=15, verbose_name='Apellido Paterno'),
        ),
        migrations.AlterField(
            model_name='postulacion',
            name='cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.cargo_postular', verbose_name='Cargo a postular'),
        ),
        migrations.AlterField(
            model_name='postulacion',
            name='celular',
            field=models.IntegerField(verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='postulacion',
            name='comuna',
            field=models.IntegerField(choices=[[0, 'Santiago'], [1, 'Providencia'], [2, 'Las Condes'], [3, 'La Florida'], [4, 'Ñuñoa'], [5, 'Vitacura'], [6, 'Maipú'], [7, 'Puente Alto'], [8, 'La Reina'], [9, 'Peñalolén'], [10, 'Macul'], [11, 'San Joaquín'], [12, 'La Cisterna'], [13, 'Independencia'], [14, 'Cerrillos'], [15, 'Renca'], [16, 'Quinta Normal'], [17, 'Lo Prado'], [18, 'Pudahuel']], verbose_name='Comuna donde vive'),
        ),
        migrations.AlterField(
            model_name='postulacion',
            name='describir_experiencia',
            field=models.TextField(verbose_name='Describa su Experiencia'),
        ),
        migrations.AlterField(
            model_name='postulacion',
            name='disponibilidad',
            field=models.BooleanField(verbose_name='Disponiblidad inmediata'),
        ),
        migrations.AlterField(
            model_name='postulacion',
            name='edad',
            field=models.IntegerField(verbose_name='Edad'),
        ),
        migrations.AlterField(
            model_name='postulacion',
            name='email',
            field=models.EmailField(max_length=30, verbose_name='Correo Electronico'),
        ),
        migrations.AlterField(
            model_name='postulacion',
            name='experiencia',
            field=models.IntegerField(choices=[[0, 'De 0 a 2 años'], [1, 'De 3 a 5 años'], [2, 'De 6 a 8 años'], [3, 'Sobre 9 años']], verbose_name='Experiencia en el area'),
        ),
        migrations.AlterField(
            model_name='postulacion',
            name='nivel_ed',
            field=models.IntegerField(choices=[[0, 'Basica Completa'], [1, 'Media Completa'], [2, 'Superior']], verbose_name='Nivel educacional'),
        ),
        migrations.AlterField(
            model_name='postulacion',
            name='nivel_excel',
            field=models.IntegerField(choices=[[0, 'Basico'], [1, 'Intermedio'], [2, 'Alto'], [3, 'Profesional']], verbose_name='Nivel de manejo en Excel'),
        ),
        migrations.AlterField(
            model_name='postulacion',
            name='nombre',
            field=models.CharField(max_length=15, verbose_name='Nombre'),
        ),
    ]
