# Generated by Django 4.1.3 on 2023-05-26 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_postulacion_fecha_postulacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postulacion',
            name='fecha_postulacion',
        ),
    ]
