# Generated by Django 4.1.3 on 2023-06-10 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_cliente_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='direccionenvio',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='direccionenvio',
            name='orden',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='ArticuloOrden',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Crear_Categoria',
        ),
        migrations.DeleteModel(
            name='DireccionEnvio',
        ),
        migrations.DeleteModel(
            name='Orden',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
