# Generated by Django 4.1.3 on 2023-05-26 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_postulacion_fecha_postulacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulacion',
            name='cv',
            field=models.FileField(blank=True, null=True, storage=5000, upload_to='CVs/', verbose_name='Adjuntar CV'),
        ),
    ]
