# Generated by Django 4.1.3 on 2023-05-26 23:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_postulacion_cv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postulacion',
            name='cv',
        ),
        migrations.AddField(
            model_name='postulacion',
            name='fecha_postulacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Postulacion'),
            preserve_default=False,
        ),
    ]
