# Generated by Django 4.1.3 on 2023-05-31 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_postulacion_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulacion',
            name='cv',
            field=models.FileField(null=True, upload_to='CVs', verbose_name='Adjuntar CV'),
        ),
    ]
