# Generated by Django 4.1.3 on 2023-06-01 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_postulacion_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulacion',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='CVs', verbose_name='Adjuntar CV'),
        ),
    ]
