# Generated by Django 4.1.3 on 2023-06-01 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_postulacion_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulacion',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Correo Electronico'),
        ),
    ]
