# Generated by Django 4.1.3 on 2023-06-03 21:49

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_postulacion_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulacion',
            name='celular',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='postulacion',
            name='describir_experiencia',
            field=models.TextField(max_length=250, verbose_name='Describa su Experiencia'),
        ),
    ]
