# Generated by Django 4.1.3 on 2023-06-11 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_carrito_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='cantidad',
            new_name='quantity',
        ),
    ]
