# Generated by Django 4.1.3 on 2023-06-12 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_payment_orderplaced'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplaced',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='orderplaced',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='orderplaced',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='orderplaced',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='OrderPlaced',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
