# Generated by Django 4.1.3 on 2023-07-10 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_orderplaced_cliente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='precio',
        ),
    ]
