# Generated by Django 4.1.3 on 2023-06-03 22:46

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_postulacion_celular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulacion',
            name='celular',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Ejemplo: +56 9 45216387 o 9 45216387', max_length=128, region=None, unique=True, verbose_name='Celular'),
        ),
    ]
