# Generated by Django 4.1.3 on 2023-06-04 00:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_postulacion_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulacion',
            name='edad',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='La edad no puede ser negativa.'), django.core.validators.MaxValueValidator(100, message='La edad no puede ser mayor a 100.')], verbose_name='Edad'),
        ),
    ]
