# Generated by Django 4.1.3 on 2023-06-07 19:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_postulacion_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulacion',
            name='comuna',
            field=models.IntegerField(choices=[[0, 'Santiago'], [1, 'Providencia'], [2, 'Las Condes'], [3, 'La Florida'], [4, 'Ñuñoa'], [5, 'Vitacura'], [6, 'Maipú'], [7, 'Puente Alto'], [8, 'La Reina'], [9, 'Peñalolén'], [10, 'Macul'], [11, 'San Joaquín'], [12, 'La Cisterna'], [13, 'Independencia'], [14, 'Cerrillos'], [15, 'Renca'], [16, 'Quinta Normal'], [17, 'Lo Prado'], [18, 'Pudahuel']], verbose_name='Comuna donde vives'),
        ),
        migrations.AlterField(
            model_name='postulacion',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='CVs', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])], verbose_name='Adjuntar Currículum Vitae'),
        ),
        migrations.AlterField(
            model_name='postulacion',
            name='describir_experiencia',
            field=models.TextField(help_text='Máximo 250 caracteres.', max_length=250, verbose_name='Describa su Experiencia'),
        ),
        migrations.AlterField(
            model_name='postulacion',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Correo Electrónico'),
        ),
    ]
