# Generated by Django 4.1.3 on 2023-06-07 20:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_alter_postulacion_ap_materno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulacion',
            name='email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='Ingresa una dirección de correo electrónico válida.')], verbose_name='Correo Electrónico'),
        ),
    ]
